# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0011_portal_has_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('google_username', models.CharField(blank=True, max_length=64, unique=True)),
                ('google_password', models.CharField(blank=True, max_length=64)),
                ('ingress_SACSID', models.CharField(max_length=1024)),
                ('ingress_csrf_token', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal', to='ingress.Portal'),
        ),
        migrations.AlterField(
            model_name='action',
            name='portal_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_to', to='ingress.Portal'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]

