# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0012_auto_add_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]

