# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0013_account_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ingress_payload_v',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]

